version: '1.0'

services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo:sis-bank-mongo-1
 
  mongo:
    image: mongo
    command: mongod --auth
    environment:
        MONGO_INITDB_ROOT_USERNAME: sisbank
        MONGO_INITDB_ROOT_PASSWORD: sisbank123
    volumes:
        - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
