spring:
    application:
        name: sis-bank-users
    config:
        activate:
          on-profile:
          - dev
    data:
        mongodb:
            database: sis-bank
            uri: mongodb://sisbank:sisbank123@swiftpay-mongo-1:27017
    security:
        user: 
            name: user
            password: user
    datasource:
        secret: ${API_SECRET:shar2122}
    mail:
        host: smtp.gmail.com
        port: 587
        username: shmins.156@gmail.com
        password: hrxftjfbexelzeye
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
eureka:
    client:
        service-url:
            defaultZone:
                http://localhost:8761/eureka
server:
    port: 8082
