spring:
    config:
        activate:
          on-profile:
          - test
    data:
        mongodb:
            database: sis-bank-test
            host: localhost
            port: 27017
server:
    port: 8082

